const authTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SIGN_OUT_USER: "SIGN_OUT_USER",
    ON_AUTH_START: "ON_AUTH_START",
    ON_AUTH_FAIL: "ON_AUTH_FAIL",
    ON_SIGN_UP_SUCCESS: "ON_SIGN_UP_SUCCESS",
    ON_SIGN_IN_SUCCESS: "ON_SIGN_IN_SUCCESS",
};

export default authTypes;
